const axios = require('axios');

const amazonMusicTrackIds = async (tracks) => {
    const searchPromises = tracks.map(track => trackId(track));
    const trackIds = [];
    await Promise.all(searchPromises).then(responses => {
        responses.forEach( response => {
            if (response.data.data && response.data.data.searchTracks && response.data.data.searchTracks.edges.length > 0) {
                trackIds.push(response.data.data.searchTracks.edges[0].node.id);
            }
        })
    });
    return trackIds;
};

const trackId = async (t) => {
        const body = {
            searchFilters: [{
                field: 'artistName',
                query: `${t.artist}`,
            }, {
                field: 'name',
                query: `${t.name}`,
            }],
            limit: 1
        };
        const axiosConfig = {
            headers: {
                'Content-Type': 'application/json',
                'x-api-key': process.env.AM_API_KEY,
                'Authorization': `Bearer ${process.env.AM_API_TOKEN}`,
            },
            timeout: 15000,
            url: 'https://api.music.amazon.dev/v1/search/tracks',
            path: '/v1/search/tracks',
        };
        return axios.post(axiosConfig.url, body, axiosConfig);
};

const newPlaylist = async (playlistName) => {
    const body = {
        title: playlistName,
        description: 'One More Playlist for You generated by AI.',
        visibility: 'PRIVATE'
    };
    const axiosConfig = {
        headers: {
            'Content-Type': 'application/json',
            'x-api-key': process.env.AM_API_KEY,
            'Authorization': `Bearer ${process.env.AM_API_TOKEN}`,
        },
        timeout: 15000,
        url: 'https://api.music.amazon.dev/v1/playlists',
        path: '/v1/playlists',
    };
    const playlistResponse = await axios.post(axiosConfig.url, body, axiosConfig);
    return playlistResponse.data.data.createPlaylist.id;
};


const appendTracks = async (playlistId, trackIds) => {
    const body = {
        trackIds,
        addDuplicateTracks: false,
    };
    const axiosConfig = {
        headers: {
            'Content-Type': 'application/json',
            'x-api-key': process.env.AM_API_KEY,
            'Authorization': `Bearer ${process.env.AM_API_TOKEN}`,
        },
        timeout: 15000,
        url: `https://api.music.amazon.dev/v1/playlists/${playlistId}/tracks`,
        path: `/v1/playlists/${playlistId}/tracks`,
    };
    return axios.put(axiosConfig.url, body, axiosConfig);
};

module.exports = { amazonMusicTrackIds, newPlaylist, appendTracks };
